### ISSUE TITLE
Argument in numpy.rint do not look right

### ISSUE THREAD

**Issue by Gabriel-p** [numpy/numpydoc#108]
See https://docs.scipy.org/doc/numpy/reference/generated/numpy.rint.html, this is what I mean:

> numpy.rint(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'rint'>

There's a backlash, asterisk, and other stuff that looks foreign to me.

**Comment by pv** [comment]
This report is specific to numpy, and should be submitted to the issue 
tracker at https://github.com/numpy/numpy

**Comment by Gabriel-p** [comment]
Done https://github.com/numpy/numpy/issues/9660
