### ISSUE TITLE
There's a 'None' string at the top of the docs

### ISSUE THREAD

**Issue by Gabriel-p** [numpy/numpydoc#109]
I'm seeing here https://docs.scipy.org/doc/numpy/index.html a 'None' located at the top left of the site.

**Comment by jnothman** [comment]
I don't think this is an issue in numpydoc. Perhaps bring it up at https://github.com/scipy/scipy.org/?

**Comment by pv** [comment]
If it's not visible on *all* numpydoc projects, which apparently is the case, then the right place for bugreport is https://github.com/numpy/numpy/ since that's where the documentation source is.

**Comment by pv** [comment]
Opened https://github.com/numpy/numpy/issues/9676
