### ISSUE TITLE
Unnecessary renaming of references

### ISSUE THREAD

**Issue by astrofrog** [numpy/numpydoc#114]
Numpydoc now renames references even when this is not needed. For example, a reference originally called ``Scargle2012`` has now been renamed in the Astropy docs:

<img width="618" alt="screen shot 2017-10-10 at 22 49 07" src="https://user-images.githubusercontent.com/314716/31412565-82d8d07a-ae0d-11e7-82f0-007534f1089a.png">

Is this intentional? Should we be using only numerical reference names? Or is it a bug since there are no duplicates of this reference so no reason to rename it?

**Comment by stefanv** [comment]
This is not necessary.  The initial de-duplication script used numerical references for simplicity, but there's no reason why that *has* to be the case.

**Comment by astrofrog** [comment]
@stefanv - ok, thanks! Just to be clear, in this case this may actually be a regression since in the rest of the docstring the reference is referred to by ``Scargle2012_`` and those references were not updated, so now give warnings when building the docs.

**Comment by stefanv** [comment]
I just read the code, and it does special case for anything other than numeric references.  I guess it will transform it to something like `Scargle20120`.  What warning do you see?

**Comment by jnothman** [comment]
The current logic seems to replace integer reference like `[5]` with `[R5]`; and a non-integer reference like `[Einstein]` with `[Einstein6]` if this is the 7th docstring being processed. Is this logic as intended??

**Comment by jnothman** [comment]
Sorry, I misread the code.

**Comment by jnothman** [comment]
@astrofrom shouldn't you be referring to it by `[Scargle2012]_` rather than `Scargle2012_`?

Still, there's no way to determine if there *will* be a duplicate and also mangle the references in a single pass over the docstrings. We could allow the first appearance of a reference to not be mangled, if there is little risk in tracking all references ever mentioned. We could also insert some delimiter between the existing reference and the added number in the non-numeric case.

**Comment by jnothman** [comment]
> ok, thanks! Just to be clear, in this case this may actually be a regression since in the rest of the docstring the reference is referred to by Scargle2012_ and those references were not updated, so now give warnings when building the docs.

The mangling here should only affect those references that are listed with `.. [xxx]` in the docstring...
