### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by jnothman** [numpy/numpydoc#129]
We of scikit-learn would like to see 0.8 released to make block markup in attribute descriptions work. I've tried to close a few issues and pull requests by creating a few of my own, and I would welcome these being reviewed and merged before release, but none is essential.

I don't have the keys to pypi, so I won't be completing the release.

**Comment by rgommers** [comment]
Thanks for all the PRs!

+1 for doing 0.8 soon. 

> I don't have the keys to pypi, so I won't be completing the release.

That can be fixed if you're interested:)

I could do the release otherwise, but probably not in the next week (enough release activity lately, need to catch up on a few other things)

**Comment by jnothman** [comment]
Well, I'm done submitting PRs for now. #136 fixes the most substantial bug. I hope to take what I have open to merge, unless there is controversy, then release. Would be nice if this is done in the next month or so.

**Comment by rgommers** [comment]
Will do some testing now with master plus the following 3 PRs (the ones that look like they can be merged now without much effort):

- gh-144 (parameter names ending in `_`)
- gh-155 (escaping `*` and `**`)
- gh-160 (use `inspect.isdatadescriptor`)

If that all looks good, I'll try to push v0.8.0 out the door. The one PR that was marked for it (gh-67 on duplicate sections) doesn't look ready; as soon as it is we can cut a new release.

**Comment by rgommers** [comment]
Looked all good for numpy and scipy docs.

**Comment by rgommers** [comment]
Okay, done. Let's not wait as long with 0.9.0!
