### ISSUE TITLE
Warn when section ordering is not according to spec

### ISSUE THREAD

**Issue by jnothman** [numpy/numpydoc#139]
in #121 we added documentation suggesting that docstring sections should be in specified order.

This should be augmented with a warning when the sections are out of order. This was the consensus at #68.

**Comment by rth** [comment]
Somewhat related section ordering is now enforced in `numpydoc.validate` checker.

**Comment by larsoner** [comment]
Indeed, I think we should close this and people should use the validation function to check things like this. It's going to be a lot more usable than trying to read warnings during a Sphinx build.
