### ISSUE TITLE
dependency on sphinx.ext.autosummary

### ISSUE THREAD

**Issue by anntzer** [numpy/numpydoc#141]
It appears that numpydoc has a hard dependency on sphinx.ext.autosummary being active (it inserts some `.. autosummary::` directives).  This is fine, but perhaps `numpydoc.setup` should just call `sphinx.ext.autosummary.setup` in that case?  (in the sense that I don't see much of a point in erroring out instead, which is the current behavior if sphinx.ext.autosummary is not listed in conf.py)

**Comment by jnothman** [comment]
Strictly this is only true if numpydoc_show_class_members is true (which it is by default) add numpydoc processes class docstrings, or if the class docstrings explicitly list methods.

But assuming there is minimal risk in automatically installing autosummary, I am +1 for this.

**Comment by anntzer** [comment]
I guess you can even delay loading sphinx.ext.autosummary until the point where you actually know you'll need it, but that seems a bit overengineering it.

**Comment by pv** [comment]
Is calling other extension's setup.py the right way to do extension 
dependencies in Sphinx?

**Comment by anntzer** [comment]
Apparently autosummary is happy to declare itself a dependency on autodoc in the same manner: https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/autosummary/__init__.py#L623 so I guess that should be safe...

**Comment by jnothman** [comment]
Would you like to submit a PR? Thanks

**Comment by anntzer** [comment]
Nah, you get to do it :-) (no hurry)
