### ISSUE TITLE
New PyPI release needed to solve incompatibility with the latest PyPI release of Sphinx

### ISSUE THREAD

**Issue by jacksonllee** [numpy/numpydoc#157]
The latest Sphinx v1.7.0 (released on PyPI in Feb 2018) has made changes ([by removing `sphinx.util.compat` since v1.7.0b1](http://www.sphinx-doc.org/en/master/changes.html#release-1-7-0-released-feb-12-2018)) that break the current PyPI release of numpydoc v.0.7.0. It [looks](https://github.com/numpy/numpydoc/blob/d5cd548964d406276fa3412469ad6acc91f4da5e/numpydoc/numpydoc.py) like the latest `numpydoc.py` on GitHub doesn't import `sphinx.util.compat` anymore, and so it would be great to release a new version of numpydoc on PyPI.

**Comment by charris** [comment]
Version v0.7.0 looks to be working with NumPy, see https://github.com/numpy/numpy/pull/10596.

**Comment by jacksonllee** [comment]
Ah, my bad, sorry. It looks like what I've observed was due to something else. Closing this issue.
