### ISSUE TITLE
Python 3.2 compatibility

### ISSUE THREAD

**Issue by siebenkopf** [numpy/numpydoc#16]
I recently downloaded the HEAD version of numpydoc to use it to create documentation in our packages. Everything works out nicely when using python 2.7.3.

However, when I tried to use numpydoc with python 3.2.3, I get the following error:

RuntimeError: Python version 2.6, 2.7 or >= 3.3 required.

After removing this check in the setup.py, I find everything working as expected. Hence, I am not sure if python 3.3 is really required, or if python 3.2 is also supported.

Could you please double-check this?

Thanks
Manuel

**Comment by rgommers** [comment]
Hi Manuel, there's a difference between "works" and "supported". Supported also means testing all changes with that version and fixing version-specific issues for it. Python 3.2 isn't really used anymore, misses some features that both 2.7 and 3.3 have, and even Python core devs recommend supporting >= 3.3, therefore I don't think it's worth spending any effort on it.

**Comment by rgommers** [comment]
Note, also numpy itself already dropped Python 3.2 support.

**Comment by siebenkopf** [comment]
Agreed. In the meantime we also stopped supporting Python 3.2. In fact, we found a different solution for our documentation. 

Thanks anyways for the feedback
Manuel
