### ISSUE TITLE
BUG?: References always have an errant second link

### ISSUE THREAD

**Issue by larsoner** [numpy/numpydoc#169]
Why do the references have a link that points nowhere? For example for this:

http://scipy.github.io/devdocs/generated/scipy.signal.windows.dpss.html#id1

Each ref is used once but there are two links, the second of which points to a tag that does not seem to exist.

**Comment by jnothman** [comment]
Presumably #136 needed more testing. It's not obvious to me what's creating
this issue. #134 is possibly also related...

**Comment by larsoner** [comment]
On `master` for my minimal example code [min.zip](https://github.com/numpy/numpydoc/files/1900504/min.zip) it looks like:
```
[1] | (1, 2) Hyvarinen, A., 1999. Fast and robust fixed-point algorithms for independent component analysis. IEEE transactions on Neural Networks, 10(3), pp.626-634.
```
I checked out the commit that immediately preceded #136 (21a194e9b42ebe95a70475e35cb69bcb4801ff36) and it still occurs and looks like:

```
[R1] | (1, 2) Hyvarinen, A., 1999. Fast and robust fixed-point algorithms for independent component analysis. IEEE transactions on Neural Networks, 10(3), pp.626-634.
```
So the problem appears to precede your PR.

**Comment by jnothman** [comment]
thanks for thoroughly debunking my kneejerk guess! I see that you're right.

I can fix the bug locally by reverting 0970cdbd.

firstly this may be deemed a sphinx/docutils bug since the backref is used
despite being in a LaTeX only environment.

Secondly we only need this hack where a reference is not otherwise cited,
but that solution may be a bit hacky.

**Comment by jnothman** [comment]
another way this might work nicely is by hacking the doctree rather than
the reST. sorry I only have time to throw out ideas and not to implement atm

**Comment by jnothman** [comment]
Another option might be to pass builder information into SphinxDocString and only generate this latex-only code if in a latex builder, rather than relying on reST directives.
