### ISSUE TITLE
including special methods in methods table

### ISSUE THREAD

**Issue by jairideout** [numpy/numpydoc#17]
When generating the "Methods" table for a class, numpydoc appears to ignore methods that start with an underscore, with the exception of `__call__`. Is there a way to have special methods (e.g., `__getitem__`, `__str__`, etc.) included in the methods table? If not, is there interest in having this option added? I may be able to work on this.

**Comment by jnothman** [comment]
I suspect this is not an issue with numpydoc, but with autoclass usage: there is a `:special-members:` flag described at http://www.sphinx-doc.org/en/stable/ext/autodoc.html.

**Comment by jnothman** [comment]
I hope this can be solved with autoclass. Closing.
