### ISSUE TITLE
Generating a docstring from a numpydoc object

### ISSUE THREAD

**Issue by hmaarrfk** [numpy/numpydoc#186]
Do you provide a way to generate a docstring from a numpydoc object?

I tried looking through the docs (and source) and I couldn't find anything of that sort.

**Comment by jnothman** [comment]
str(numpydocstring)?

**Comment by hmaarrfk** [comment]
Whoa, so cool.

Is there a way to get it closer to a round trip? That is, removing the restructured text formatting?

I would like to append the docs of a function, but allow other python modules to keep parsing them.

**Comment by jnothman** [comment]
I'm not sure what you mean... I don't think you should get much ReST
formatting with numpydoc.docscrape.NumpyDocString

#67 has discussion on merging docstrings, which may be a future feature, if
that's what you're talking about

**Comment by hmaarrfk** [comment]
Cool seems appropriate! Thanks
