### ISSUE TITLE
Question: Is include the `_str_signature` necessary in the `__str__`

### ISSUE THREAD

**Issue by hmaarrfk** [numpy/numpydoc#190]
https://github.com/numpy/numpydoc/blob/659e43f2a4885de2e6def5649f1cdb6208d3e8f4/numpydoc/docscrape.py#L471

It doesn't seem natural for one to write their own signature. I would think that the `str(NumpyDocString)` would return the same thing that one would type themselves.

Can we take out the `_str_signature`?

Once again, this is in reference to designing a solution for:
https://github.com/numpy/numpydoc/pull/67#issuecomment-341268415

Otherwise, one would need an other function that doesn't include the `_str_signature()` line.

**Comment by pv** [comment]
No, if the original docstring contained the signature also the formatted one needs to contain it.

**Comment by hmaarrfk** [comment]
I guess the question relates to roundtripping (PR #189):

```python
# Signature example

from numpydoc.docscrape import FunctionDoc

def foo(bar='baz'):
    """foo does foo-like stuff

    Parameters
    ----------
    bar : str
        bar like stufff

    """
    return bar


doc = FunctionDoc(foo)

print(str(doc))
```
output:
```
.. function:: foo
    

foo(bar='baz')

foo does foo-like stuff

Parameters
----------
bar : str
    bar like stufff

.. index::
```

I expected it to return something like the original doc-string I typed in.

I understand if this isn't the desired usecase of numpydoc.

I understand if this

**Comment by pv** [comment]
Perhaps --- however, please keep in mind that numpydoc has a single task that it is meant to do, generating Sphinx-formatted docstrings from Numpy-format ones, and any changes should not cause regressions to this functionality.

**Comment by hmaarrfk** [comment]
Got it. I'll keep that in mind when I try to think of a good way to integrate this kind of functionality.
