### ISSUE TITLE
"Validating NumpyDoc docstrings" out of date?

### ISSUE THREAD

**Issue by wsfulton** [numpy/numpydoc#198]
Is the documentation at https://numpydoc.readthedocs.io/en/latest/validation.html out of date? Using numpydoc-0.8.0 I get:
```
$ python -m numpydoc numpy.ndarray
python: No module named numpydoc.__main__; 'numpydoc' is a package and cannot be directly executed
```
I don't see any `__main__` methods under the numpydoc package which might be a replacement.

**Comment by jnothman** [comment]
I think those "latest" docs reference the development version, not the
latest stable release. We should probably show stable docs on rtd

**Comment by stefanv** [comment]
This now matches the latest release.

**Comment by cs947** [comment]
I have gotten this problem again. Can someone verify if this still matches the latest and greatest?
