### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by henry0312** [numpy/numpydoc#203]
There has not been a new release for about a year.
https://github.com/numpy/numpydoc/releases

**Comment by jnothman** [comment]
This looks like a good idea. @pv, @rgommers?

**Comment by rgommers** [comment]
That makes sense to me. I probably could do that towards the end of this week.

@jnothman there's a number of PRs open that look useful, mainly from you. No one else unfortunately had much bandwidth to review. Would it make sense to merge some of those before a new release? I can try to look at the most important ones.

**Comment by jnothman** [comment]
So are we okay to push this out as it is? Do we need to throw together a change log?

**Comment by larsoner** [comment]
> So are we okay to push this out as it is?

It would be good to get in #161 and #164 before pushing out a release.

> Do we need to throw together a change log?

It would be nice to do this for people. I ran:
```
$ github_changelog_generator numpy/numpydoc --unreleased-only
```
And saw a lot of PRs in the category "Merged pull requests", so I took 10 min to label the merged PRs, re-ran, and now get something that can probably be copy-pasted/adjusted to give something usable without too much more work:

--------

# Change Log

## [Unreleased](https://github.com/numpy/numpydoc/tree/HEAD)

[Full Changelog](https://github.com/numpy/numpydoc/compare/v0.8.0...HEAD)

**Implemented enhancements:**

- ENH: accept autoclass member options [\#205](https://github.com/numpy/numpydoc/pull/205) ([mattip](https://github.com/mattip))
- Clarify location of certain invalid docstrings. [\#200](https://github.com/numpy/numpydoc/pull/200) ([anntzer](https://github.com/anntzer))
- Make parameter a namedtuple [\#176](https://github.com/numpy/numpydoc/pull/176) ([timhoffm](https://github.com/timhoffm))
- ENH: Added support for multiple functions+description in a See Also block [\#172](https://github.com/numpy/numpydoc/pull/172) ([pvanmulbregt](https://github.com/pvanmulbregt))
- DOC: Added example of multi-line code in Examples section. [\#168](https://github.com/numpy/numpydoc/pull/168) ([pvanmulbregt](https://github.com/pvanmulbregt))
- switch the test suite to pytest [\#166](https://github.com/numpy/numpydoc/pull/166) ([ev-br](https://github.com/ev-br))
- Require that sphinx issue no warnings in CI [\#153](https://github.com/numpy/numpydoc/pull/153) ([jnothman](https://github.com/jnothman))
- Command-line tool to help debug NumpyDocString [\#146](https://github.com/numpy/numpydoc/pull/146) ([jnothman](https://github.com/jnothman))
- Support Receives section for generator.send\(...\) params [\#145](https://github.com/numpy/numpydoc/pull/145) ([jnothman](https://github.com/jnothman))

**Fixed bugs:**

- References messed up [\#177](https://github.com/numpy/numpydoc/issues/177)
- BUG?: References always have an errant second link [\#169](https://github.com/numpy/numpydoc/issues/169)
- BUG: turn member descriptor attributes into links [\#201](https://github.com/numpy/numpydoc/pull/201) ([mattip](https://github.com/mattip))
- FIX: Fix collections.abc imports [\#195](https://github.com/numpy/numpydoc/pull/195) ([larsoner](https://github.com/larsoner))
- FIX: Escape chars in re [\#194](https://github.com/numpy/numpydoc/pull/194) ([larsoner](https://github.com/larsoner))
- Fix markup in format.rst. [\#193](https://github.com/numpy/numpydoc/pull/193) ([anntzer](https://github.com/anntzer))
- Move setup of autosummary earlier in setup\(\). [\#191](https://github.com/numpy/numpydoc/pull/191) ([anntzer](https://github.com/anntzer))
- Only print the index if it is necessary. [\#187](https://github.com/numpy/numpydoc/pull/187) ([hmaarrfk](https://github.com/hmaarrfk))
- FIX pedantic handling of whitespace in reference regex [\#181](https://github.com/numpy/numpydoc/pull/181) ([jnothman](https://github.com/jnothman))
- FIX remove duplicated citation back-references [\#180](https://github.com/numpy/numpydoc/pull/180) ([jnothman](https://github.com/jnothman))
- Use DEDUPLICATION\_TAG to determine whether a citation node is in a docstring [\#179](https://github.com/numpy/numpydoc/pull/179) ([jnothman](https://github.com/jnothman))
- FIX parsing of type-only return params [\#175](https://github.com/numpy/numpydoc/pull/175) ([timhoffm](https://github.com/timhoffm))
- pip --use-wheel no longer exists [\#174](https://github.com/numpy/numpydoc/pull/174) ([jnothman](https://github.com/jnothman))
- DOC: Add missing backslash to omega for inline math example. [\#171](https://github.com/numpy/numpydoc/pull/171) ([pvanmulbregt](https://github.com/pvanmulbregt))
- DOC: remove links to numpy repo file [\#167](https://github.com/numpy/numpydoc/pull/167) ([mattip](https://github.com/mattip))
- Escape the \* in \*args and \*\*kwargs [\#155](https://github.com/numpy/numpydoc/pull/155) ([has2k1](https://github.com/has2k1))

**Closed issues:**

- autosummary fails with numpydoc where napoleon succeeds [\#204](https://github.com/numpy/numpydoc/issues/204)
-  NumpyDocString doesn't roundtrip well [\#188](https://github.com/numpy/numpydoc/issues/188)
- Generating a docstring from a numpydoc object [\#186](https://github.com/numpy/numpydoc/issues/186)
- make parameters and attributes anchors in docstrings [\#185](https://github.com/numpy/numpydoc/issues/185)
- BUG: Plot\(s\) not rendered if docstring ends with normal text after show command [\#162](https://github.com/numpy/numpydoc/issues/162)
- Location reporting returns useless information [\#115](https://github.com/numpy/numpydoc/issues/115)
- Anonymous return values have their types populated in the name slot of the tuple.  [\#72](https://github.com/numpy/numpydoc/issues/72)
- support for coroutine [\#47](https://github.com/numpy/numpydoc/issues/47)
- multiple entries in a See Also section [\#28](https://github.com/numpy/numpydoc/issues/28)

**Comment by jorisvandenbossche** [comment]
> It would be good to get in #161 and #164 before pushing out a release.

I will try to get to #161 this evening or tomorrow (and also try to build the pandas docs with numpydoc master)

**Comment by jorisvandenbossche** [comment]
Updated the PR, and tested numpydoc master with the pandas docs. This seems to go fine (apart from a few cases where numpydoc got stricter in parsing the See Also, but those were actual mistakes in our docs)

**Comment by rgommers** [comment]
0.9.0 is up, closing. thanks all for getting all PRs in!

**Comment by rgommers** [comment]
question: should be make the next version number 0.10.0 or 1.0.0?

**Comment by larsoner** [comment]
I'm fine with either. If forced to choose I'd go with 1.0.0

**Comment by rgommers** [comment]
@larsoner apologies, I overlooked your Changelog. That still looks useful to put on https://github.com/numpy/numpydoc/releases/tag/v0.9.0 and send out to the mailing list. I'll see if I can add the last few PRs we merged.

**Comment by jnothman** [comment]
Thanks @rgommers for pulling it together. Sorry I was not more available at this point.

**Comment by rgommers** [comment]
@jnothman no worries at all - you and @larsoner did most of the heavy lifting for this release!

**Comment by henry0312** [comment]
Thank you a lot.
