### ISSUE TITLE
Header Formatting

### ISSUE THREAD

**Issue by kyleabeauchamp** [numpy/numpydoc#21]
So this question is more about the interplay between typical sphinx themes (e.g. RTD) and the numpy docstring formatting.  I've found that a lot of themes don't properly format some section headers such as `Notes`.  For example:

http://mdtraj.org/latest/api/generated/mdtraj.utils.ensure_type.html#mdtraj.utils.ensure_type

Does anyone have any suggestions on finding themes that are compatible with these headers?  (PS I know this is probably not a bug on your end, but I thought I'd post here.)

**Comment by jnothman** [comment]
Is this still an issue? Those headers are marked up with `<p class="rubric">`

**Comment by jnothman** [comment]
Closing. Feel free to reopen.
