### ISSUE TITLE
AttributeError: 'module' object has no attribute 'getLogger'

### ISSUE THREAD

**Issue by Alphadelta14** [numpy/numpydoc#210]
We just pulled in a new version of numpydoc and our CI started breaking everywhere with
```
00:00:52.522 + sphinx-build -M html docs docs/_build
00:00:53.001 Running Sphinx v1.5.6
00:00:53.001 making output directory...
00:00:53.864 
00:00:53.864 Exception occurred:
00:00:53.865   File "/home/jenkins-slave/virtualenvs/executor-0/autotest-builder/local/lib/python2.7/site-packages/numpydoc/numpydoc.py", line 44, in <module>
00:00:53.865     logger = logging.getLogger(__name__)
00:00:53.865 AttributeError: 'module' object has no attribute 'getLogger'
00:00:53.866 The full traceback has been saved in /tmp/sphinx-err-Gw1CKi.log, if you want to report the issue to the developers.
00:00:53.866 Please also report this if it was a user error, so that a better error message can be provided next time.
00:00:53.866 A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

This does not appear to be a Sphinx issue, but rather an issue with the latest numpydoc.

**Comment by rgommers** [comment]
The minimum Sphinx version you need is 1.6, you have 1.5.6. Can you try upgrading?

**Comment by rgommers** [comment]
Ah this is my fault, `setup.py` still has `install_requires=["sphinx >= 1.2.3`

**Comment by rgommers** [comment]
Should do a 0.9.1 bugfix release for that I think.

**Comment by jnothman** [comment]
Do we need to change the Sphinx version requirements, or just fall back to
using python logging (rather than Sphinx)?

>
>

**Comment by rgommers** [comment]
I think bumping the minimum Sphinx version is good anyway, there have been so many Sphinx releases (both minor and bugfix and since a few months a 2.0) that it doesn't really make sense to keep compatibility with that many versions.

**Comment by rgommers** [comment]
Also, IIRC some versions between 1.2.3 and 1.5.x are broken. We have to pin to 1.2.3 for a long time in SciPy.

**Comment by rgommers** [comment]
Or we could keep it to 1.2.3 with a fallback to avoid more people the trouble of upgrading. But then let's document that 1.2.3 works, and if we need a bump for some other reason we'll go to 1.6.5 or higher.

**Comment by rgommers** [comment]
@jnothman @larsoner, others - opinions? I'd like to release 0.9.1 with a fix by the end of today.

**Comment by jnothman** [comment]
I'm happy to bump to 1.6

**Comment by rgommers** [comment]
Okay, thanks @jnothman. `0.9.1` is up, and master is updated to version number `1.0.0.dev0`
