### ISSUE TITLE
Documentation on RTD is outdated

### ISSUE THREAD

**Issue by saimn** [numpy/numpydoc#212]
I could not find the new xref options in the docs, it looks like it does not build on RTD since 10 months:
https://readthedocs.org/projects/numpydoc/builds/
Probably a github/rtd configuration issue, which may need to be updated to use webhooks.

**Comment by rgommers** [comment]
Hmm odd, we have no RTD config file, only a `doc/requirements/txt` that was added for readthedocs according to a commit message. We just need to fix the trigger.

**Comment by rgommers** [comment]
I have rebuilt: https://numpydoc.readthedocs.io/en/latest/format.html says 23 April 2019

xref docs at https://numpydoc.readthedocs.io/en/latest/install.html

**Comment by rgommers** [comment]
Ah:
```
Your project, ..., needs to be reconfigured in order to continue building automatically after January 31st, 2019. For more information, see our documentation on webhook integrations. 
```
Fun.

**Comment by rgommers** [comment]
https://docs.readthedocs.io/en/latest/webhooks.html#i-was-warned-that-my-project-won-t-automatically-build-after-april-1st

**Comment by rgommers** [comment]
Okay webhook updated, closing.

Thanks for the report @saimn

**Comment by saimn** [comment]
Thanks for the quick update @rgommers !
