### ISSUE TITLE
References outside function

### ISSUE THREAD

**Issue by Hoxbro** [numpy/numpydoc#214]
I have seen a similar problem as mentioned [here](https://github.com/numpy/numpydoc/issues/177#issuecomment-487175646). Problem is for docstrings but only for docstrings outside of functions. I have attached an [example](https://github.com/numpy/numpydoc/files/3123855/numpydoctest2.zip), and by running the command `sphinx-build -b singlehtml -d _build/doctrees . _build/singlehtml` l i get the following for output:
![56817105-2daf3500-6845-11e9-9571-f758848d6cc7](https://user-images.githubusercontent.com/19758978/56849625-39f3ca80-68f7-11e9-996e-9071f685855f.png)

If I delete `:members:` from manual.rst the docstring outside the function works as expected.
<img width="975" alt="Screenshot 2019-04-27 at 14 21 26" src="https://user-images.githubusercontent.com/19758978/56849678-cacaa600-68f7-11e9-9a13-3ebde1db6933.png">

Am i doing anything wrong? I'm running the newest version (0.9.1).

**Comment by sebp** [comment]
I observed the same using `sphinx==1.7.9` and `numpydoc==0.9.1`, the reference is rendered correctly for [a function](https://scikit-survival.readthedocs.io/en/latest/generated/sksurv.kernels.clinical_kernel.html#sksurv.kernels.clinical_kernel), but is messed up when used in [a class](https://scikit-survival.readthedocs.io/en/latest/generated/sksurv.kernels.ClinicalKernelTransform.html#sksurv.kernels.ClinicalKernelTransform).

**Comment by MatthewFlamm** [comment]
I have the same issue with version 0.9.1 for a reference in a class.  I'm glad @sebp came up with a minimal working version so I didn't have to :smile: .   I reverted to version 0.8.0 and all works as expected.

**Comment by larsoner** [comment]
Are either of you comfortable enough with `git` to do a `git blame` to isolate the commit that causes this issue?

**Comment by MatthewFlamm** [comment]
I thought I was, but your comment makes me question that.  I thought that `git blame` requires knowledge of what file or line is suspected to cause the issue.  Did you mean `git bisect`?

**Comment by larsoner** [comment]
Argh yes, sorry. `git bisect` is what I meant

**Comment by larsoner** [comment]
(I don't mean to scare you off -- it can be difficult for people totally unfamiliar with `git` but if you've already used `git` before you'll probably be fine.)

**Comment by MatthewFlamm** [comment]
I'll give it a try.  Although I first need to figure out how to get my environment to work with a development version of numpydoc, as I currently have it installed from pypi.  Is it as simple as cloning the repo and then `pip install -e numpydoc`?

**Comment by larsoner** [comment]
Usually I use `pip install -e .` after cloning and `cd` to the clone dir.

**Comment by larsoner** [comment]
(But looking at it I guess this would be functionally equivalent!)

**Comment by sebp** [comment]
According to my investigation, commit c8513c5db6088a305711851519f944b33f7e1b25 is to blame.

**Comment by MatthewFlamm** [comment]
Beat me to it.  This is the same commit that breaks functionality for me.

**Comment by Hoxbro** [comment]
I seem to have fixed this issue: 

![image](https://user-images.githubusercontent.com/19758978/79117252-eb02a780-7d8a-11ea-9c95-f2e3950f753e.png)

**Comment by larsoner** [comment]
@Hoxbro do you want to open a PR to fix it?

**Comment by dizcza** [comment]
I still have this problem https://pytorch-mighty.readthedocs.io/en/latest/reference/loss.html

**Comment by Hoxbro** [comment]
I think your problem is related to #130, which is also commented in the documentation https://numpydoc.readthedocs.io/en/latest/format.html.

**Comment by dizcza** [comment]
@Hoxbro 
The workaround posted in #130, unfortunately, does not help. Now it parses the references in an overview section as [Rfe594912252b-R1] instead of [Rfe594912252b-1].

**Comment by Hoxbro** [comment]
What I was trying to say is that there have been some problems with reference in tables for a long time. 

If I were you I will make a new issue with a minimal working example.
