### ISSUE TITLE
function signatures for *args, **kwargs objects off

### ISSUE THREAD

**Issue by rgommers** [numpy/numpydoc#218]
The function listing at http://scipy.github.io/devdocs/stats.html#continuous-distributions looks good (that's with 0.8.0). 0.9.0 now adds `*args, **kwargs` as function signature for each entry, which looks ugly.

First seen in https://github.com/scipy/scipy/pull/10116#issuecomment-488252166

**Comment by larsoner** [comment]
Looks like this is fixed in 1.0
