### ISSUE TITLE
Rendering of single backquotes?

### ISSUE THREAD

**Issue by sciunto** [numpy/numpydoc#233]
In scikit-image, we observed that single-backquotes are not rendered in a browser. The full behavior, including the analysis of the generated html code can be seen here: https://github.com/scikit-image/scikit-image/issues/4117

Based on this section: https://numpydoc.readthedocs.io/en/latest/format.html#common-rest-concepts : 

> Variable, module, function, and class names should be written between single back-ticks (`numpy`)

However, as you can see in your example, it is not rendered by a browser : https://numpydoc.readthedocs.io/en/latest/example.html#example

Is this intentional? Can we tune the behavior? I much prefer the rendering of double backquotes for variable names...

Thanks!

**Comment by jnothman** [comment]
This has nothing to do with numpydoc. You can define a default_role in your
Sphinx conf.

**Comment by sciunto** [comment]
Thanks for the hint!
