### ISSUE TITLE
Timing of next release

### ISSUE THREAD

**Issue by sofroniewn** [numpy/numpydoc#249]
One of the projects I'm working on is interested in leveraging the import speed improvements in https://github.com/numpy/numpydoc/pull/248 (see discussion here https://github.com/napari/napari/issues/758) and I was wondering when the next planned numpydoc release was that would include this. Thanks so much!!

**Comment by rgommers** [comment]
> I was wondering when the next planned numpydoc release was that would include this

There's not really a planned release cycle for `numpydoc`. A question like yours is usually the trigger. It's about time I'd say. Reading the linked issue, it's a little surprising that you'd need to import numpydoc for something other than "build me some docs". 

The next milestone we have open is 1.0.0, for which we may want to do some more thorough testing ....
Alternatively, we could do a 0.9.2 with just the fix you need in it. @numpy/numpydoc-devs any preference?

**Comment by sofroniewn** [comment]
We're using numpydoc inside our GUI based application to parse some doc strings and then show them to the user in a GUI window when requested.

We'd certainly be fine with an `0.9.2` release that only contained #248. Thanks so much for the quick response!

**Comment by larsoner** [comment]
I'm fine with a 0.9.2 with the fix backported

**Comment by bashtage** [comment]
I would vote for a 1.0 (or 0.10) if no one wants to commit to stability.  statsmodels has to use git to get correct docstrings.

**Comment by rgommers** [comment]
Why don't we do both. There's one unresolved open issue for 1.0.0 (gh-215), and even if we choose to ignore that we'll need a decent about of testing. Let's try to do that in the next week or two.

Doing 0.9.2 will take 30 minutes or so, let's make that a Christmas present for Napari:)

**Comment by rgommers** [comment]
`0.9.2` is on PyPI, and I pushed a `0.9.x` branch and the `v0.9.2` tag.

**Comment by rgommers** [comment]
> I would vote for a 1.0 (or 0.10) if no one wants to commit to stability.

I think 1.0 is fine. A lot of the instability anyway comes from Sphinx, not much we can do about that. Our aim is to keep Numpydoc stable.

**Comment by sofroniewn** [comment]
> let's make that a Christmas present for Napari:)

Thanks!!

**Comment by prisae** [comment]
> Why don't we do both. There's one unresolved open issue for 1.0.0 ([gh-215](https://github.com/numpy/numpydoc/issues/215)), and even if we choose to ignore that we'll need a decent about of testing. Let's try to do that in the next week or two.

Would be great if #215 could be resolved for a hopefully soonish v1.0.0. Is there already a fix for #215? Is there anything one could help with, e.g., testing?

**Comment by rgommers** [comment]
gh-215 isn't yet resolved. It's a bit of a mess, because there are multiple reports and the fix that works for some doesn't work for others. Help with testing, merging the proposed CSS fix, and then summarizing what issues remain would be super helpful

**Comment by larsoner** [comment]
Looks like #215 is now just a documentation problem. I say let's document it and release, hopefully next week.

**Comment by larsoner** [comment]
We've released 1.0 since this issue was opened and there is now another issue about pushing out a 1.1 so I'll close this
