### ISSUE TITLE
Missing reference to float_power function in the ufunc list

### ISSUE THREAD

**Issue by hippo91** [numpy/numpydoc#250]
Hi and thank you for your remarkable work on `numpy` and its doc.
Forgive me if i'am not posting in the right place.
In the list of available `ufunc` functions i do not see any entry concerning the `float_power` function.
However it seems that this function has all the attributes of a `ufunc` instance.
I'm i wrong?
Thanks again.

**Comment by rossbar** [comment]
Hi @hippo91 , I think this issue may need to be raised in the numpy repo. Note that the `numpydoc` repo deals with numpy's sphinx extension, not the documentation for numpy itself. For issues with numpy's documentation, open an issue in the official [numpy repo](https://github.com/numpy/numpy)

**Comment by hippo91** [comment]
@rossbar thank you for your answer. I will open an issue in the `numpy` repo.

**Comment by hippo91** [comment]
numpy/numpy#15214
