### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by thequackdaddy** [numpy/numpydoc#270]
Thanks for merging #221. 

I think it might make sense to have a release sooner rather than later. Dependent projects are either using workarounds to keep their docbuild working.

**Comment by jnothman** [comment]
Agreed. I'm not yet sure when I'd have time to pursue this.

>

**Comment by larsoner** [comment]
I can probably push one out. 1.1 sound good to everyone?

**Comment by jnothman** [comment]
I think those two thumbs up mean "yes, please"

**Comment by jnothman** [comment]
Thanks @larsoner!

**Comment by thequackdaddy** [comment]
Thanks to everyone.
