### ISSUE TITLE
multiple entries in a See Also section

### ISSUE THREAD

**Issue by ev-br** [numpy/numpydoc#28]
Observed in scipy.interpolate docs

```
See Also
------------
splev, splrep : FITPACK wrappers
```

The description text (the stuff after the colon) does not show up in the generated html docs.

Moving the description to a separate line,

```
See Also
------------
splev, splrep 
             FITPACK wrappers
```

 does not help either

**Comment by ev-br** [comment]
Apparently, this is a feature, not a bug. At least precisely this behavior is asserted by tests:
https://github.com/numpy/numpydoc/blob/master/numpydoc/tests/test_docscrape.py#L574

FWIW I actually wonder why

**Comment by jnothman** [comment]
I don't see where this behaviour is/was tested at https://github.com/numpy/numpydoc/blob/96a0fe3/numpydoc/tests/test_docscrape.py#L574...
