### ISSUE TITLE
pypi archive file permissions too strict

### ISSUE THREAD

**Issue by minusf** [numpy/numpydoc#31]
i am trying to package 0.5 for openbsd and it seems that the files in the archive
have needlessly strict permissions that need to be overriden to be useful for `site-packages`:
```
-rw-r-----  1 user  group  5959 Jul 24  2013 LICENSE.txt
-rw-r-----  1 user  group    52 Jul 24  2013 MANIFEST.in
-rw-r-----  1 user  group   522 Jun  8  2014 PKG-INFO
-rw-r-----  1 user  group  1913 Jun  8  2014 README.rst
drwxr-x---  3 user  group   512 Jun  8  2014 numpydoc
drwxr-x---  2 user  group   512 Jun  8  2014 numpydoc.egg-info
-rw-r-----  1 user  group    59 Jun  8  2014 setup.cfg
-rw-r-----  1 user  group  1029 Jun  8  2014 setup.py
```
would be possible to have `644/755` instead of `640/750` please?

**Comment by minusf** [comment]
this command should take care of it:
```sh
$ chmod -R a+rX
```

**Comment by rgommers** [comment]
I can't find a good description of what the recommend file permissions for tarballs on PyPi are, except that only files installed as scripts should be executable. ``-rw-rw-r--`` (``664``) seems more reasonable than what we have now, and that's what almost all files in ``numpy`` & ``scipy`` have.

Anyone object to changing it to that?

**Comment by pv** [comment]
644 or 664 should be ok

**Comment by rgommers** [comment]
There's nothing to fix here it looks like. Git doesn't store complete file permissions, and a fresh checkout of ``numpydoc`` gives me:

    $ ls -l
    total 24
    -rw-rw-r-- 1 rgommers rgommers 5959 Jan 31 21:58 LICENSE.txt
    -rw-rw-r-- 1 rgommers rgommers   52 Jan 31 21:58 MANIFEST.in
    drwxrwxr-x 3 rgommers rgommers 4096 Jan 31 21:58 numpydoc
    -rw-rw-r-- 1 rgommers rgommers 2183 Jan 31 21:58 README.rst
    -rw-rw-r-- 1 rgommers rgommers 1033 Jan 31 21:58 setup.py
    $ ls -l numpydoc/
    total 128
    -rw-rw-r-- 1 rgommers rgommers  5417 Jan 31 21:58 comment_eater.py
    -rw-rw-r-- 1 rgommers rgommers 24740 Jan 31 21:58 compiler_unparse.py
    -rw-rw-r-- 1 rgommers rgommers 18072 Jan 31 21:58 docscrape.py
    -rw-rw-r-- 1 rgommers rgommers  9527 Jan 31 21:58 docscrape_sphinx.py
    -rw-rw-r-- 1 rgommers rgommers    94 Jan 31 21:58 __init__.py
    -rw-rw-r-- 1 rgommers rgommers  2507 Jan 31 21:58 linkcode.py
    -rw-rw-r-- 1 rgommers rgommers  6693 Jan 31 21:58 numpydoc.py
    -rw-rw-r-- 1 rgommers rgommers  5854 Jan 31 21:58 phantom_import.py
    -rw-rw-r-- 1 rgommers rgommers 20530 Jan 31 21:58 plot_directive.py
    drwxrwxr-x 2 rgommers rgommers  4096 Jan 31 21:58 tests
    -rw-rw-r-- 1 rgommers rgommers  4310 Jan 31 21:58 traitsdoc.py

So those will be the permissions for the 0.6 tarballs.
