### ISSUE TITLE
Anchors for individual sections in numpydoc doc?

### ISSUE THREAD

**Issue by zmoon** [numpy/numpydoc#317]
It would be nice to have those. The [Sections](https://numpydoc.readthedocs.io/en/latest/format.html#sections) section is pretty long. It would be easier to share the description of a specific numpydoc section if they each had their own anchor links.

**Comment by rossbar** [comment]
Agreed, this would definitely make the docs more navigable. Switching from an enumerated list to headings for each of the elements should do it.
