### ISSUE TITLE
RTD configuration - `latest`

### ISSUE THREAD

**Issue by zmoon** [numpy/numpydoc#321]
I mentioned this in the #320 thread, but it seems like the RTD settings need to be updated to reflect the default branch name change. The last [RTD build](https://readthedocs.org/projects/numpydoc/builds/) was more than a month ago. I would like to enjoy the recent updates (#320, etc.).

**Comment by larsoner** [comment]
I tweaked the setting to say "main" is the "latest" branch and now it's building:

https://readthedocs.org/projects/numpydoc/builds/13569752/

**Comment by zmoon** [comment]
@larsoner, interestingly, in the new RTD build, I see the theme issues that I mentioned in #318. Do you? This is strange because I see from the log that the latest pydata-sphinx-theme was used.

**Comment by larsoner** [comment]
Yeah, I wonder if it's because we build with an ancient Sphinx (1.8.5)

**Comment by larsoner** [comment]
All better https://numpydoc.readthedocs.io/en/latest/example.html via direct push commit https://github.com/numpy/numpydoc/commit/5b3b4a4abe7fd46c8f647d17ab7e6adc091d8b9c (the only way I could think of to reasonably test a fix)
