### ISSUE TITLE
``numpydoc_validation_checks``  not running in sphinx build

### ISSUE THREAD

**Issue by nstarman** [numpy/numpydoc#326]
In https://github.com/astropy/astropy/pull/11597, we've tried turning on a number of validation flags in ``numpydoc_validation_checks``.  When ``python -m numpydoc numpy.ndarray —validate`` is run on a specific astropy object, the expected set of errors are raised, but nothing seems to happen in sphinx builds. Any insight would be appreciated.

**Comment by rossbar** [comment]
Ah, I think there's a mismatch between the latest docs and the current release - the documentation at https://numpydoc.readthedocs.io/en/latest/ is for the development (1.2-dev) version; the numpydoc validation features aren't yet available in the latest stable release (v1.1).

**Comment by nstarman** [comment]
Thanks for the quick diagnosis!

**Comment by jarrodmillman** [comment]
@nstarman A new release is planned for Monday, it would be great if you could test out the release candidate:
https://pypi.org/project/numpydoc/1.2rc1/

It would be great to hear whether the validation flags work for you now.

**Comment by nstarman** [comment]
Thanks @jarrodmillman.
We've been having some issues in the astropy version with some of our dynamically generated docstrings, so it's actually been quite difficult to test the numpydoc validation features. It's on my list to figure out where the problems arise, because it would be great to use numpydoc v1.2 in astropy!
