### ISSUE TITLE
v0.6 tag?

### ISSUE THREAD

**Issue by tacaswell** [numpy/numpydoc#33]
I would like to start using the `Yields` section without having to deal with source installs.

This seems like it is getting more and more relevant with the up-tick of python 3 in the scientific community.

**Comment by rgommers** [comment]
It's been 10 months since v0.5, so looks like it's about time for a new release anyway.

**Comment by rgommers** [comment]
@pv I can do this if you agree - I'll need rights for PyPi though.

**Comment by jairideout** [comment]
:+1: for an updated release on PyPI, this would be handy for our project

**Comment by lmjohns3** [comment]
+1 It would be great to be able to use the "Yields" section on readthedocs!

**Comment by Korijn** [comment]
Anyone working on this?

**Comment by Xarthisius** [comment]
Just hit a bug with 0.5 (returning metadata is required for parallel builds), can we please get that release?

**Comment by rgommers** [comment]
@pv ping. I'm still happy to do it. Even if you do this release, it would still be good to add a few maintainers to the numpydoc package on pypi; the bus factor is a bit low now.

**Comment by rgommers** [comment]
Version 0.6.0 is tagged and up at https://pypi.python.org/pypi/numpydoc.
