### ISSUE TITLE
Exclude class properties from being listed under METHODS section

### ISSUE THREAD

**Issue by ma-sadeghi** [numpy/numpydoc#339]
Currently, both "methods" and "properties" are listed under METHODS section. Is there a way to exclude "properties"?

Many thanks!

**Comment by rossbar** [comment]
Can you provide an example? AFAICT methods decorated with `@property` are listed under the `Attributes` section.

**Comment by ma-sadeghi** [comment]
Honestly, I can't remember the case for which I opened up this issue. Anyway, I just looked at our documentation, and it looks fine. So, I'm closing this issue. Thank you anyway!
