### ISSUE TITLE
Add links for references with DOIs

### ISSUE THREAD

**Issue by rmcgibbo** [numpy/numpydoc#34]
We use numpy style docstrings and numpydoc to build documentation for a couple projects that implement the methods mostly described in scientific papers. A pretty large fraction of the docstrings for our functions and methods have a 'References' section.

It would be sweet if, in the sphinx html, there were a straightforward way to render the references with a link to the paper. Obviously it would be possible to use raw restructuredtext links, but those are not very elegant to read if you're looking at the docstring in IPython.

This might be too magical, but perhaps numpydoc could look in each reference for `"doi:<whatever>"`, and use that to create a link.

cc https://github.com/msmbuilder/msmbuilder/issues/537

**Comment by pv** [comment]
http://dx.doi.org/DOI renders, cf.
https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/eigen/lobpcg/lobpcg.py#L253
http://docs.scipy.org/doc/scipy-dev/reference/generated/generated/scipy.sparse.linalg.lobpcg.html

**Comment by rmcgibbo** [comment]
Yeah, we could just put the links in the citation.

**Comment by ewmoore** [comment]
There is this gist around, https://gist.github.com/jonls/b910afc46473b02597c4
I haven't tried using it though.

**Comment by ewmoore** [comment]
Also, if someone works on this, it might also be nice to do something similar for arxiv links.

**Comment by pv** [comment]
Also, whoever wants to work on it should also consider implementing it
as a separate sphinx extension manipulating the doctree of citations,
rather than doing this in numpydoc parsing phase.

**Comment by njsmith** [comment]
I've been quite pleased with [sphinxcontrib.bibtex](https://www.google.com/search?hl=en&safe=off&client=firefox-a&hs=WSO&q=sphinxcontrib.bibtex). You can see an example in the docs for [colorspacious](https://colorspacious.readthedocs.org/en/latest/).
