### ISSUE TITLE
Release would be awesome

### ISSUE THREAD

**Issue by akaszynski** [numpy/numpydoc#355]
First off, thanks to all the maintainers/contributors here.  `numpydoc` is great!

There are a bunch of projects I maintain or contribute to that have to use the following in their requirements for building docs.

```
https://github.com/numpy/numpydoc/archive/main.zip  # need latest
```

Would be nice if we could have a release at some point in the near future to let me finally use a strict version of `numpydoc`.

**Comment by rgommers** [comment]
Thanks for asking, it's been a while. Should be fine to tag `1.2.0` I think. @numpy/numpydoc-devs is there any reason not to release current HEAD?

**Comment by larsoner** [comment]
Agreed we should release

**Comment by jarrodmillman** [comment]
I am happy to help w/ the release if folks want.

**Comment by jarrodmillman** [comment]
@larsoner I can take care of that.  I think the only thing I can't do myself is upload to PyPI (unless you want to give me permission).  I am happy to take care of a few releases (over the next few years).

I am going to release pygraphviz 1.8 later today.  Once I finish that, I will take a look at this.

**Comment by larsoner** [comment]
Invitation sent, assuming your PyPi username matches your GitHub one!

**Comment by jarrodmillman** [comment]
That is me and I've accepted the invitation.

**Comment by jarrodmillman** [comment]
https://pypi.org/project/numpydoc/1.2rc1/

**Comment by akaszynski** [comment]
Thanks!
