### ISSUE TITLE
1.2: change tagging convention?

### ISSUE THREAD

**Issue by kloczek** [numpy/numpydoc#360]
Looks like with latest version tagging conventoion has been changed from `v<version>` to release-<version>`.
Is it possible to back to original convention or add additionale tag `v1.2`?

**Comment by rgommers** [comment]
Yes that looks wrong. I think we can remove the tags that were just added. @jarrodmillman any reason not to do that?

**Comment by jarrodmillman** [comment]
@kloczek I've added a lightweight `v1.2.0` tag:
https://github.com/numpy/numpydoc/releases/tag/v1.2.0

I will update the release notes to use the `v1.x.x` tags going forward.

**Comment by kloczek** [comment]
Thank you 😄
