### ISSUE TITLE
Support numpydoc validation without running sphinx

### ISSUE THREAD

**Issue by akaszynski** [numpy/numpydoc#364]
Is there a way to run the numpydoc validation without running sphinx? I'd like to have a separate CI step to validate docstrings for an entire directory (recursively), but I don't see an option to do this.

**Comment by rossbar** [comment]
Yes, this is possible, e.g.

```python
>>> from numpydoc.validate import validate
>>> vdict = validate("numpy.sum")
>>> vdict["errors"]
[('ES01', 'No extended summary found'),
 ('RT02',
  'The first line of the Returns section should contain only the type, unless multiple values are being returned'),
 ('SA04', 'Missing description for See Also "mean" reference'),
 ('SA04', 'Missing description for See Also "average" reference')]
```

Just replace "numpy.sum" with the function you want to run docstring validation on. See the docstring of `validate` for details.

**Comment by akaszynski** [comment]
Thanks!

This inspired me for something that I've been needing for some time for `pyvista` and several `pyansys` projects. I've created a repo [numpydoc-validation](https://github.com/pyvista/numpydoc-validation) and a package to generate numpydoc validation reports . Please let me know if you or the rest of your team sees any issue with this.
