### ISSUE TITLE
Validation check YD01 not implemented properly

### ISSUE THREAD

**Issue by martinlackner** [numpy/numpydoc#365]
Hello!

The validation check YD01 is not implemented properly. The specific code in `validate.py` is the following:

https://github.com/numpy/numpydoc/blob/f33a53e64f9c92bc81353a9682f796d7485a4ed7/numpydoc/validate.py#L599

Since `doc.method_source` also contains the docstring, this condition is also satisfied if "yield" occurs in the docstring (where it might be used as a regular word).

I have encountered this bug in a function that did not contain a `yield` and it took me quite a while to figure out what was wrong.

**Comment by jnothman** [comment]
Also fires a false alarm when there is a generator nested within the function, or when a variable name includes "yield". Rather we should be using `inspect.isgeneratorfunction`
