### ISSUE TITLE
1.4.0 release plan

### ISSUE THREAD

**Issue by jarrodmillman** [numpy/numpydoc#408]
Unless there are objections, I plan to release 1.4.0 soon (see tentative plan below). The main change is supporting newer versions of docutils, which I think we should get out now that other packages (e.g., sphinx) support it.

- [x] release pydata-sphinx-theme 0.9 (6/78)
- [x] numpydoc-1.4rc1 (6/8)
- [x] numpydoc-1.4 (6/9)

**Comment by rossbar** [comment]
I think a 1.4.0 is warranted to for the docutils issue that was fixed in #403 , so +1 for getting that out soon.
