### ISSUE TITLE
Is numpydoc_use_blockquotes deprecated or not yet?

### ISSUE THREAD

**Issue by mscheltienne** [numpy/numpydoc#420]
On the documentation website for version 1.5.dev0: https://numpydoc.readthedocs.io/en/latest/install.html#configuration

> numpydoc_use_blockquotes : bool
> 
>     Until version 0.8, parameter definitions were shown as blockquotes, rather than in a definition list. 
>     If your styling requires blockquotes, switch this config option to True. 
>     This option will be removed in version 0.10.

And we are on version 1.4/1.5, so does this key still exists?
Could you update the configuration documentation? 🙏

**Comment by larsoner** [comment]
Looking at the code I'm not sure if anyone using this param as `True` would have gotten a warning about it, but I guess they would have had to *add* that param to get that behavior back and seen the doc warning about it. So +1 for removing it for 1.5.0.

@rossbar @jarrodmillman thoughts? If you agree then @mscheltienne would you be up for a quick PR to remove it?

**Comment by larsoner** [comment]
Clearly I'm reading my GitHub emails in the wrong order as @jarrodmillman had a PR for this already :)
