### ISSUE TITLE
Parsing `returns` section with several types and no name

### ISSUE THREAD

**Issue by MaozGelbart** [numpy/numpydoc#428]
According to numpydoc [return value specification](https://numpydoc.readthedocs.io/en/latest/format.html#returns), the name for each return value may be optional. If the return value is omitted and the return type can take several types (if the actual type depends on user input, for example), then if the second type contains `" :"` as part of the type description (as in the following example) it is incorrectly identified as parameter type separator. This prevents sphinx recognition of the referenced type. 

```python
from numpydoc.docscrape import NumpyDocString
docstr="""
Returns
-------
str or :class:`NumpyDocString`
"""
print(NumpyDocString(docstr))
```
Results with:
```



Returns
-------
str or : class:`NumpyDocString`

```

I would expect getting the following result:
```



Returns
-------
str or :class:`NumpyDocString`

```

The example is using version 1.4.0.
I think this was changed in #286 .

Thanks!

**Comment by rossbar** [comment]
Thanks for reporting @MaozGelbart and for providing the detailed background info, I agree with your diagnosis and I think #429 should be sufficient to fix the issue of role parsing when there are no parameter names.
