### ISSUE TITLE
BUG: Numpydoc doesn't render attributes decorated with `cached_property` in the Attributes section

### ISSUE THREAD

**Issue by tirthasheshpatel** [numpy/numpydoc#432]
Numpydoc doesn't render attributes decorated with `cached_property` in the `Attribute` section. I think it is due to this line:

https://github.com/numpy/numpydoc/blob/b138ea7758532a8b6950c4404570ab367c3919f4/numpydoc/docscrape.py#L709

which can be changed to:

```
from functools import cached_property

...


                    func is None
                    or isinstance(func, property)
                    or isinstance(func, cached_property)
                    or inspect.isdatadescriptor(func)
```

to fix the issue.

xref scipy/scipy#16002

**Comment by larsoner** [comment]
Seems reasonable to me, could you make a pr @tirthasheshpatel ?
