### ISSUE TITLE
readthedocs build failing

### ISSUE THREAD

**Issue by jarrodmillman** [numpy/numpydoc#439]
@larsoner @stefanv Would one of you mind giving me access to https://readthedocs.org/projects/numpydoc/ ?

My login is jarrodmillman. If you prefer to fix it yourself, I think the only issue is that `doc/requirements.txt` is now `requirements/doc.txt`.

**Comment by stefanv** [comment]
Access given

**Comment by jarrodmillman** [comment]
I've updated the settings and it is building now.

**Comment by jarrodmillman** [comment]
Updated https://numpydoc.readthedocs.io/en/latest/
