### ISSUE TITLE
style of `[1]` is strange in numpydoc docs

### ISSUE THREAD

**Issue by njzjz** [numpy/numpydoc#443]
See https://numpydoc.readthedocs.io/en/latest/format.html#id8

![image](https://user-images.githubusercontent.com/9496702/197369203-ed3c6b0c-823e-4276-88ac-5df508b8024e.png)

Here obviously, the left and right brackets have different styles - different colors and different text sizes.

**Comment by larsoner** [comment]
To me this seems like a theme problem moreso than a numpydoc one. I do not see this in other packages such as this one

https://mne.tools/dev/generated/mne.preprocessing.regress_artifact.html

**Comment by rossbar** [comment]
I agree - I rebuilt the docs locally with the latest `requirements/doc.txt` which gives `pydata-sphinx-theme=0.11` and didn't see this issue.

Redeploying the docs with the latest dependencies should fix this.

**Comment by njzjz** [comment]
It looks that this issue has been resolved.
