### ISSUE TITLE
Documenting a class - method table not correct

### ISSUE THREAD

**Issue by cmeeren** [numpy/numpydoc#45]
I am building my docs on readthedocs using numpydoc. When documenting a class, unless I set ``numpydoc_show_class_members=False`` in ``conf.py``, there is a table where the method names are in the leftmost column, and nothing in the rightmost column. Is this an issue with numpydoc? See image below. The page in question is [here](http://apexpy.readthedocs.org/en/latest/reference/Apex.html#apexpy.Apex.geo2qd) (I've hidden the table now).

![rendered](https://cloud.githubusercontent.com/assets/7766733/11312976/dccd5e10-8fd9-11e5-8a44-d5a2ec005fd1.png)

Previously posted on https://github.com/snide/sphinx_rtd_theme/issues/264

**Comment by pv** [comment]
sphinx.ext.napoleon and numpydoc should probably not be used at the same time.

**Comment by pv** [comment]
The actual reason appears to be that you are missing `.. currentmodule:: apexpy` from the source .rst file.

**Comment by cmeeren** [comment]
Thanks! I removed `sphinx.ext.napoleon` which solved quite a few things.
