### ISSUE TITLE
Ignore specific functions

### ISSUE THREAD

**Issue by HealthyPear** [numpy/numpydoc#455]
The issue's subject is somewhat general, but my particular use case is that of a script.

Usually, we write a script as,

```python
"""Module docstring"""

import bla

def main():

    # do stuff

if __name__ == "__main__":

    main()
```

I am using numpydoc via its Sphinx extension and I get

`XXX.main:GL08:The object does not have a docstring`

Technically, yes, it should have one, but it would be the same as the module dosctring in this case.

I don't know if there is any kind of convention about this particular case.

If there isn't, is there a way I can tell the checker to ignore e.g. the `main` function of a script?

**Comment by larsoner** [comment]
Have you tried `numpydoc_validation_exclude`? If you have function names that are distinct enough it might work for you (and/or you could make the names distinct enough like `script_main` or something)

**Comment by rossbar** [comment]
Agreed - running the doc build with docstring validation results in more nits from the validator. There are several [configuration values to help control this](https://numpydoc.readthedocs.io/en/latest/install.html#configuration), such as the aforementioned `numpydoc_validation_exclude` which allows you to skip validation on certain functions (like `main`) or `numpydoc_validation_checks` with which you can skip specific checks (e.g `GL08`).

Hopefully this answers the question, so I'll go ahead and close this. If not, please feel free to reopen with followup info.
