### ISSUE TITLE
Unify cli validation interfaces

### ISSUE THREAD

**Issue by stefanv** [numpy/numpydoc#467]
See https://github.com/numpy/numpydoc/pull/454

`python -m numpydoc`
`python -m numpydoc.hooks.validate_docstrings`

These CLI interfaces do slightly different things, but one could imagine a command word interface a-la git.

Also, it would be good to expose this as an executable user-script `numpydoc`.

/cc @stefmolin

**Comment by stefmolin** [comment]
I'll tackle this one after #466

**Comment by stefmolin** [comment]
Is there a preference between these two options?

```shell
$ numpydoc render           # runs the current numpydoc CLI's render_object()
$ numpydoc validate         # runs the current --validate
$ numpydoc validate --ast   # runs the current numpydoc.hooks.validate_docstrings
```

OR

```shell
$ numpydoc                    # runs the current numpydoc CLI's render_object()
$ numpydoc --validate         # runs the current --validate
$ numpydoc --ast-validation   # runs the current numpydoc.hooks.validate_docstrings
```

I'm calling the hook method "ast" because it uses the abstract syntax tree unlike the original validation, but let me know if we should use something else.

**Comment by stefanv** [comment]
How about:

```
$ numpydoc  # alias for numpydoc render
$ numpydoc render
$ numpydoc validate
```

**Comment by stefmolin** [comment]
And `numpydoc validate` would have the flag to trigger the hook version?

**Comment by stefanv** [comment]
Or just drop the alias; it's not like this is done so often by hand.

**Comment by stefmolin** [comment]
Looking at this more, I actually don't think the `--validate` logic should be combined with the hook logic because they operate on different inputs: the hook takes files and the `--validate` option takes a dotted path, which could be to anything.

How about having separate subcommands for each?

```shell
$ numpydoc render
$ numpydoc validate
$ numpydoc hook
```

**Comment by stefanv** [comment]
Nice and clean; I prefer that too.

**Comment by stefanv** [comment]
`hook` is perhaps not a super intuitive name; `numpydoc lint`?
