### ISSUE TITLE
circleci-artifacts-redirector-action error

### ISSUE THREAD

**Issue by jarrodmillman** [numpy/numpydoc#469]
@larsoner The CircleCI artifact redirector hasn't worked in the last few weeks (it last worked 4 month ago):
https://github.com/numpy/numpydoc/actions/workflows/main.yml?page=2

For example, here
https://github.com/numpy/numpydoc/actions/runs/5392536984/jobs/9791034918
we are getting this error:
```
Run larsoner/circleci-artifacts-redirector-action@master
  with:
    repo-token: ***
    artifact-path: 0/html/index.html
    circleci-jobs: build_docs
Error: Cannot read properties of undefined (reading 'length')
```

**Comment by stefanv** [comment]
Missing CIRCLECI_TOKEN:

```
$ cat .github/workflows/main.yml
on: [status]
jobs:
  circleci_artifacts_redirector_job:
    runs-on: ubuntu-latest
    name: Run CircleCI artifacts redirector
    steps:
      - name: GitHub Action step
        uses: larsoner/circleci-artifacts-redirector-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-path: 0/html/index.html
          circleci-jobs: build_docs
```

**Comment by stefanv** [comment]
NetworkX version (working):

Needs, under `repo-token`:

```
          api-token: ${{ secrets.CIRCLECI_ARTIFACT_REDIRECTOR_TOKEN }}
```

**Comment by stefanv** [comment]
From the [docs](https://github.com/marketplace/actions/run-circleci-artifacts-redirector):

> The api-token needs to be a [CircleCI personal API token](https://app.circleci.com/settings/user/tokens) (not a project token as it is not supported yet in API v2!) whose value has been added to the GitHub secrets of your repository (e.g., as CIRCLE_TOKEN), e.g. for the MNE-Python project this would be https://github.com/mne-tools/mne-python/settings/secrets/actions.

**Comment by jarrodmillman** [comment]
Thanks @stefanv !! Someone with access for this repo will need to make the update.

**Comment by seberg** [comment]
I created a CirceCI token and set the secret, maybe try close/reopen on a PR?

But, since you are the one making releases, etc. we should probably just add @jarrodmillman as an admin for numpydoc.  Right now it's just @larsoner (and the numpy owners).

**Comment by jarrodmillman** [comment]
@seberg Having admin privileges of numpydoc would be helpful.
