### ISSUE TITLE
support for coroutine

### ISSUE THREAD

**Issue by Dreem-Devices** [numpy/numpydoc#47]
I have a lot of coroutine to comment but i have not seen any suppport for this python feature.

The yield allows to comment what goes out of the coroutine but it would be nice to be able to specify what goes in in a specific manner.

**Comment by stefanv** [comment]
What syntax do you suggest?
​

**Comment by jnothman** [comment]
A "Receives" heading and parameter listing perhaps??

**Comment by stefanv** [comment]
Does it make sense to bundle this under the yield description?

**Comment by jnothman** [comment]
> Does it make sense to bundle this under the yield description?

In the sense that the signature should describe one or a tuple of arguments to be passed to a function, it does not belong in yield. It is another parameter listing, with type specs and descriptions.

**Comment by stefanv** [comment]
I guess I'd need a concrete code snippet example to wrap my head around this.

**Comment by jnothman** [comment]
A bit artificial, but perhaps:

```python
def optimize(n_params):
    """Supplies candidates to search in response to error signal

    Parameters
    ----------
    n_params : int

    Yields
    ------
    candidate : array of shape (n_params,)

    Given
    -----
    error : float
    """

    candidate = np.random.rand(n_params)
    error = yield candidate
    while not_converged():
        candidate = generate_new_candidate(candidate, error)
        results = yield candidate




optimizer = optimize(10)
candidate = next(optimizer)
while True:
    try:
        candidate = optimizer.send(evaluate(candidate))
    except StopIteration:
        break
```

**Comment by stefanv** [comment]
I can't find any language around this in the documentation, so `Receives` works for me.

**Comment by jnothman** [comment]
Yes, receives makes some sense. @dreem-devices, any opinion?

**Comment by jnothman** [comment]
@tacaswell, you +1ed the issue. Do you have an opinion on the section naming? "Receives" okay?

**Comment by tacaswell** [comment]
I like `Receives`, `Sent` could also make sense (as you `.send` the values in).  

co-routines also need to support `Return`, I assume that is ok, but was not included in the example above.
