### ISSUE TITLE
citation replacement in mangle_docstrings fails with more than 9 citations

### ISSUE THREAD

**Issue by sergiocallegari** [numpy/numpydoc#49]
Citations are recognized according to the following docstring

```
'^.. \\[([a-z0-9_.-])\\]'
```

Clearly, this only matches when there is a single char between the square brackets.
With this, the following logic

```
# start renaming from the longest string, to avoid overwriting parts
references.sort(key=lambda x: -len(x))
```

is never used.  Furthermore, such sorting does not seem to be necessary anyway, since the citations
are replaced /including/ the square brackets:

```
lines[i] = lines[i].replace(sixu('[%s]_') % r,
                            sixu('[%s]_') % new_r)
```

which should be enough to assure that reference keys are never overwritten in parts.

**Comment by stefanv** [comment]
Thanks for describing this issue.  Do you mind filing a pull request to fix it?

**Comment by sergiocallegari** [comment]
I see that the pull is not being merged. Is the bug in the process of being fixed otherwise? Is there anything I can do to improve the pull request if it is not up to the project standard?

**Comment by stefanv** [comment]
@sergiocallegari Sorry, having only two authors is the bottleneck.

**Comment by jnothman** [comment]
I think this can be closed

**Comment by rgommers** [comment]
thanks, closed
