### ISSUE TITLE
Documentation for Excluding 

### ISSUE THREAD

**Issue by RNKuhns** [numpy/numpydoc#498]
Found a potential bug. I'm noticing the following pattern for excluding a method as shown in docs is generating a malformed toml error:

```toml
exclude = [
    "\.__init__$",
]
```

But if I use the following it is working.

```toml
exclude = [
    "__init__$",
]
```

Is that happening for anyone else?

**Comment by RNKuhns** [comment]
Note that this may be related to how toml handles single and double quoted strings differently.

**Comment by stefmolin** [comment]
You are correct this is due to the difference between single and double quotes in TOML. If you want to use a regular expression, you must use single quotes.
