### ISSUE TITLE
numpydoc isn't really documented.

### ISSUE THREAD

**Issue by NelleV** [numpy/numpydoc#66]
It'd be nice to move the numpydoc documentation outside the numpy repository and have a proper website on read the doc.
That should be quite easy to do and if of interest to the numpydoc community, be assigned to a URAP student here at BIDS? (@stefanv, what do you think?)

**Comment by stefanv** [comment]
It would be good to have some documentation, mentioning how to use the project, how to potentially extend it, pitfalls (currently multiple thread builds), etc.

**Comment by pv** [comment]
https://numpydoc.readthedocs.io/en/latest/

**Comment by NelleV** [comment]
Nice! Thanks!
