### ISSUE TITLE
Some files are not compatible with Python 3

### ISSUE THREAD

**Issue by lesteve** [numpy/numpydoc#70]
In our case the numpydoc functionality does not seem to be affected as these files don't seem to be used. 

Super hacky one-liner to get the full list of problematic files:

```
for i in numpydoc/*.py; do ipython -c "import `echo ${i/.py/} | sed -e 's@/@.@'`" | grep Traceback > /dev/null || echo $i; done
```
Output:
```
numpydoc/comment_eater.py
numpydoc/compiler_unparse.py
numpydoc/phantom_import.py
numpydoc/plot_directive.py
numpydoc/traitsdoc.py
```

Most of the files are 4 years old but traitsdoc.py which is 2 years old. Are they still being used/maintained?

One I am particularly surprised by is plot_directive.py, is it really needed and how is it different from the matplotlib one?

**Comment by pv** [comment]
This is known.
.
As for plot_directive, please note the warning it emits on import.
The features added were merged back to matplotlib some years back.

**Comment by lesteve** [comment]
In our case (joblib) this is mildly annoying because we bundle numpydoc and if you are not careful enough nosetests with its automatic disovery of tests, tries to import the numpydoc modules and fails under Python 3.

Would there be any interest in PRs making them Python 3 compatible? Any idea whether their  functionalities are actually being used?

What about a PR removing plot_directive.py if the functionality has been merged in matplotlib a while ago?

**Comment by pv** [comment]
I believe these file are not widely used, so porting them to Python 3 
may not be worthwhile. I don't think deleting them will cause a large 
inconvenience for anyone.
