### ISSUE TITLE
__version__ attribute

### ISSUE THREAD

**Issue by jschueller** [numpy/numpydoc#75]
Would it be possible to get a ```__version__``` attribute to know the version ?

**Comment by stefanv** [comment]
Sure, would you like to file a PR?

**Comment by jschueller** [comment]
Should I add ```__version__ = '0.6'``` in the init.py file

**Comment by stefanv** [comment]
Maybe something like:

- https://github.com/scikit-image/scikit-image/blob/master/skimage/__init__.py#L68
- https://github.com/scikit-image/scikit-image/blob/master/setup.py#L41
