### ISSUE TITLE
Purpose of the vendored sphinx.ext.linkcode

### ISSUE THREAD

**Issue by ghisvail** [numpy/numpydoc#82]
Could you comment on this? Looks like it is used nowhere in the actual `numpydoc` code, right?

**Comment by pv** [comment]
The vendored code contains parts that are or were useful for numpy's
documentation. Indeed, that's where all this comes from. There's not much
to be gained from removing these things.

23.12.2016 18.46 "Ghislain Antony Vaillant" <notifications@github.com>
kirjoitti:

**Comment by ghisvail** [comment]
> The vendored code contains parts that are or were useful for numpy's documentation.

Could you point me to the relevant section in `numpy`? It would be nice to verify whether this code path is still in use or they switched to using `sphinx.ext.linkcode` as the warning raised by the code advised. Afterall, the availability of Sphinx >= 1.2 is a given now.

> There's not much to be gained from removing these things.

In the context of Debian packaging, the policy is to avoid proliferation of code by minimizing vendoring as much as possible. It looks to me that the current `numpydoc` can live without the bundled `linkcode`, and that client projects which rely on it could easily transition to `sphinx.ext.linkcode`, right?

**Comment by ghisvail** [comment]
Numpy actually [prioritizes](https://github.com/numpy/numpy/blob/f303ccebaa2953e506c4991825cda2ac8b5d2fb9/doc/source/conf.py#L280) on using `sphinx.ext.linkcode`, so the vendored version is no longer useful.

**Comment by rgommers** [comment]
I removed ``linkcode`` in gh-85 yesterday (without noting it closes this issue).

**Comment by rgommers** [comment]
My motivation was simpler: it's giving a ``FutureWarning`` right now when running the tests, and I was in cleanup mode.

**Comment by ghisvail** [comment]
No problem. Thanks for addressing this. Closing.
